텐서플로1

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.enable_eager_execution()

In [3]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
X = data.data
y = data.target
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float64 (569,) int32


In [5]:
# 타입 및 형태 변환.
X = np.array(X, dtype='float32')
y = np.array(y, dtype='float32')
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float32 (569,) float32


In [6]:
y = y.reshape(-1,1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [7]:
# X,y 8:2로 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
X_train

array([[1.390e+01, 1.924e+01, 8.873e+01, ..., 8.150e-02, 2.356e-01,
        7.603e-02],
       [8.571e+00, 1.310e+01, 5.453e+01, ..., 8.512e-02, 2.983e-01,
        1.049e-01],
       [1.020e+01, 1.748e+01, 6.505e+01, ..., 3.571e-02, 2.868e-01,
        7.809e-02],
       ...,
       [1.327e+01, 1.476e+01, 8.474e+01, ..., 1.001e-01, 2.027e-01,
        6.206e-02],
       [2.351e+01, 2.427e+01, 1.551e+02, ..., 2.089e-01, 2.593e-01,
        7.738e-02],
       [2.094e+01, 2.356e+01, 1.389e+02, ..., 2.105e-01, 3.126e-01,
        7.849e-02]], dtype=float32)

In [9]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455, 1) (114, 1)


In [10]:
# 학습하기 전에 데이터 표준화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)
X_train

array([[1.390e+01, 1.924e+01, 8.873e+01, ..., 8.150e-02, 2.356e-01,
        7.603e-02],
       [8.571e+00, 1.310e+01, 5.453e+01, ..., 8.512e-02, 2.983e-01,
        1.049e-01],
       [1.020e+01, 1.748e+01, 6.505e+01, ..., 3.571e-02, 2.868e-01,
        7.809e-02],
       ...,
       [1.327e+01, 1.476e+01, 8.474e+01, ..., 1.001e-01, 2.027e-01,
        6.206e-02],
       [2.351e+01, 2.427e+01, 1.551e+02, ..., 2.089e-01, 2.593e-01,
        7.738e-02],
       [2.094e+01, 2.356e+01, 1.389e+02, ..., 2.105e-01, 3.126e-01,
        7.849e-02]], dtype=float32)

In [11]:
# sigmoid 함수 정의

def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [12]:
# w, b 초기화 시키는 객체 생성
initializer = tf.contrib.layers.xavier_initializer()

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [13]:
# w 및 b 생성
w = tf.Variable(initializer([30,1]))
b = tf.Variable(initializer([1]))

In [14]:
# 예측값 계산하기
hypothesis = tf.sigmoid(tf.matmul(train_scaled, w) + b)
hypothesis

<tf.Tensor: id=32, shape=(455, 1), dtype=float32, numpy=
array([[3.47834796e-01],
       [5.34180760e-01],
       [9.61123407e-02],
       [5.12585938e-01],
       [2.71951377e-01],
       [4.22209620e-01],
       [5.91860533e-01],
       [4.20177877e-01],
       [1.98770255e-01],
       [1.05847985e-01],
       [1.80189967e-01],
       [2.77128518e-01],
       [1.47601217e-01],
       [3.85194361e-01],
       [6.56479001e-02],
       [5.06255627e-02],
       [4.28464830e-01],
       [1.78143352e-01],
       [5.46301126e-01],
       [9.03527737e-02],
       [3.85602891e-01],
       [3.88250351e-02],
       [1.89672709e-01],
       [4.83201236e-01],
       [4.96160507e-01],
       [3.80847752e-01],
       [2.02939361e-01],
       [4.52888042e-01],
       [2.56575942e-01],
       [3.92066419e-01],
       [2.90699840e-01],
       [5.17323613e-01],
       [3.24406505e-01],
       [6.51985109e-02],
       [1.15690708e-01],
       [3.70377988e-01],
       [2.56170273e-01],
       [2.44947076

In [15]:
# optimizer 생성
optimizer = tf.train.AdamOptimizer(0.001)

In [16]:
# 반복해서 w와 b를 찾음

for step in range(100):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(train_scaled, w) + b)
        cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis))
        grads = tape.gradient(cost, [w,b])
    optimizer.apply_gradients(grads_and_vars=zip(grads, [w,b]))

    if step % 10 ==0:
        print('-'*50)
        print(f'step : {step}, cost : {cost.numpy()}, w : {w.numpy()}, b : {b.numpy()}')
        print('-'*50)


--------------------------------------------------
step : 0, cost : 0.8933848142623901, w : [[-0.34868118]
 [-0.10224021]
 [ 0.31647217]
 [ 0.1416692 ]
 [ 0.10038077]
 [-0.23194355]
 [ 0.08240257]
 [ 0.02763994]
 [-0.23255244]
 [-0.20825353]
 [-0.32424504]
 [-0.21174878]
 [-0.11801939]
 [ 0.19991283]
 [ 0.23751384]
 [-0.41845748]
 [-0.32547498]
 [ 0.0846998 ]
 [-0.2835544 ]
 [ 0.40646505]
 [ 0.04735227]
 [-0.30897993]
 [-0.37632427]
 [-0.3677434 ]
 [-0.0842912 ]
 [-0.22490259]
 [-0.03016136]
 [ 0.331087  ]
 [ 0.00467457]
 [-0.11024282]], b : [-1.7199556]
--------------------------------------------------
--------------------------------------------------
step : 10, cost : 0.8433213233947754, w : [[-0.35865855]
 [-0.11219844]
 [ 0.30649516]
 [ 0.1316912 ]
 [ 0.09041109]
 [-0.24190935]
 [ 0.07243036]
 [ 0.01766457]
 [-0.2425063 ]
 [-0.19824988]
 [-0.3342206 ]
 [-0.20174797]
 [-0.12799354]
 [ 0.18993513]
 [ 0.24748263]
 [-0.42837065]
 [-0.33539107]
 [ 0.07474368]
 [-0.2735626 ]
 [ 0.4165

In [17]:
print(w, b)

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.43848008],
       [-0.18584868],
       [ 0.22682972],
       [ 0.05143448],
       [ 0.01358586],
       [-0.31650332],
       [-0.00536504],
       [-0.06152282],
       [-0.31142667],
       [-0.11013213],
       [-0.41419986],
       [-0.11816803],
       [-0.20724265],
       [ 0.109318  ],
       [ 0.31767634],
       [-0.46531036],
       [-0.37231413],
       [ 0.00566084],
       [-0.19112347],
       [ 0.5183276 ],
       [-0.0426972 ],
       [-0.3946634 ],
       [-0.46609583],
       [-0.45824298],
       [-0.17417352],
       [-0.30983964],
       [-0.11636458],
       [ 0.24301603],
       [-0.08277405],
       [-0.1911087 ]], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-1.6270809], dtype=float32)>


In [18]:
# 뽑아낸 w, b값으로 예측하기
predict = tf.sigmoid(tf.matmul(test_scaled, w) + b)
predict01 = tf.cast(predict > 0.5, dtype=tf.float32)
predict01

<tf.Tensor: id=6436, shape=(114, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
     

In [19]:
# 예측값과 실제값이 같은지 확인후 정확도 뽑아내기
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype='float32'))
accuracy

<tf.Tensor: id=6441, shape=(), dtype=float32, numpy=0.7894737>

텐서플로2

In [20]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [21]:
tf.enable_eager_execution()

In [22]:
cancer = datasets.load_breast_cancer()
cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [23]:
X = cancer.data
y = cancer.target
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float64 (569,) int32


In [24]:
X = np.array(X, dtype='float32')
y = np.array(y, dtype='float32')
y = y.reshape(-1,1)
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float32 (569, 1) float32


In [25]:
#데이터 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455, 1) (114, 1)


In [26]:
# 표준화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

In [27]:
model = Sequential()
model.add(Dense(1, input_dim=30, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [30]:
# GradientDecent를 이용해 w와 b를 찾는 방법 설정
# loss='binary_crossentropy' :  -1 / 데이터수 * (y * np.log(hypothesis) + (1 - y) * (np.log(1 - hypothesis))) 합이 최소가 되는 w와 b를 찾음

# optimizer = Adam(learning_rate=0.001) : learning rate를 0.001로 설정
# metrics=['acc'] : 정확도를 출력

model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['acc'])

In [31]:
# 입력 값을 X, 출력값을 y로 해서 100번 반복해서 w와 b 계산
model.fit(train_scaled, y_train, epochs=100)

Train on 455 samples
Epoch 1/100
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
455/455 [==============================] - 0s 959us/sample - loss: 0.9275 - acc: 0.3824
Epoch 2/100
455/455 [==============================] - 0s 35us/sample - loss: 0.8236 - acc: 0.4791
Epoch 3/100
455/455 [==============================] - 0s 28us/sample - loss: 0.7370 - acc: 0.5758
Epoch 4/100
455/455 [==============================] - 0s 37us/sample - loss: 0.6634 - acc: 0.6659
Epoch 5/100
455/455 [==============================] - 0s 37us/sample - loss: 0.6028 - acc: 0.7275
Epoch 6/100
455/455 [==============================] - 0s 38us/sample - loss: 0.5543 - acc: 0.7670
Epoch 7/100
455/455 [==============================] - 0s 36us/sample - loss: 0.5122 - acc: 0.8000
Epoch 8/100
455/455 [==============================] - 0s 36us/sample - loss: 0.4761 - acc: 0.8242
Epoch 9/100
455/455 [==============================] - 0s 35us/sample - loss: 0.4455 - acc: 

In [40]:
pred = model.predict(test_scaled)
pred

array([[9.1899025e-01],
       [1.4279085e-01],
       [7.5322247e-01],
       [7.9278827e-01],
       [9.9085855e-01],
       [2.8468317e-01],
       [9.8205078e-01],
       [9.8985648e-01],
       [6.4671040e-06],
       [1.7881393e-07],
       [8.7924778e-01],
       [1.6507506e-04],
       [6.7910552e-04],
       [9.8338723e-04],
       [1.5473932e-01],
       [1.4146087e-01],
       [9.9091017e-01],
       [6.4255089e-02],
       [9.9693441e-01],
       [4.7683716e-07],
       [9.5932305e-01],
       [9.9962842e-01],
       [9.8110521e-01],
       [8.1199759e-01],
       [9.9513018e-01],
       [8.2863927e-01],
       [1.0895580e-02],
       [8.1968141e-01],
       [9.5605135e-01],
       [9.8183274e-01],
       [9.8908919e-01],
       [7.1183741e-03],
       [9.9071956e-01],
       [9.4161987e-01],
       [9.6354294e-01],
       [9.8379064e-01],
       [9.5306069e-01],
       [1.4552474e-03],
       [9.9404305e-01],
       [4.8241913e-03],
       [6.0177594e-02],
       [3.665685

In [41]:
predict01 = np.where(pred > 0.5, 1, 0)
predict01

array([[1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
    

In [42]:
predict02 = predict01.flatten()
predict02

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0])

In [49]:
y_test = y_test.flatten()

In [50]:
predict03 = (predict02 == y_test)
predict03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [51]:
np.sum(predict03)

112

In [47]:
np.sum(tf.cast(predict03, dtype='float32'))

7008.0

In [52]:
acc = np.sum(predict03) / len(predict03)

In [53]:
acc

0.9824561403508771