텐서플로1

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import tensorflow as tf


In [3]:
tf.enable_eager_execution()

In [5]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [14]:
X = data.data
y = data.target
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float64 (569,) int32


In [15]:
# 타입 및 형태 변환.
X = np.array(X, dtype='float32')
y = np.array(y, dtype='float32')
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float32 (569,) float32


In [16]:
y = y.reshape(-1,1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [17]:
# X,y 8:2로 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [18]:
X_train

array([[1.141e+01, 1.082e+01, 7.334e+01, ..., 8.958e-02, 3.016e-01,
        8.523e-02],
       [1.426e+01, 1.965e+01, 9.783e+01, ..., 1.505e-01, 2.398e-01,
        1.082e-01],
       [1.311e+01, 2.254e+01, 8.702e+01, ..., 1.126e-01, 4.128e-01,
        1.076e-01],
       ...,
       [1.575e+01, 2.025e+01, 1.026e+02, ..., 1.479e-01, 3.993e-01,
        1.064e-01],
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.338e+01, 3.072e+01, 8.634e+01, ..., 7.763e-02, 2.196e-01,
        7.675e-02]], dtype=float32)

In [21]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455, 1) (114, 1)


In [22]:
# 학습하기 전에 데이터 표준화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)
X_train

array([[1.141e+01, 1.082e+01, 7.334e+01, ..., 8.958e-02, 3.016e-01,
        8.523e-02],
       [1.426e+01, 1.965e+01, 9.783e+01, ..., 1.505e-01, 2.398e-01,
        1.082e-01],
       [1.311e+01, 2.254e+01, 8.702e+01, ..., 1.126e-01, 4.128e-01,
        1.076e-01],
       ...,
       [1.575e+01, 2.025e+01, 1.026e+02, ..., 1.479e-01, 3.993e-01,
        1.064e-01],
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.338e+01, 3.072e+01, 8.634e+01, ..., 7.763e-02, 2.196e-01,
        7.675e-02]], dtype=float32)

In [23]:
# sigmoid 함수 정의

def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [24]:
# w, b 초기화 시키는 객체 생성
initializer = tf.contrib.layers.xavier_initializer()

In [25]:
# w 및 b 생성
w = tf.Variable(initializer([30,1]))
b = tf.Variable(initializer([1]))

In [26]:
# 예측값 계산하기
hypothesis = tf.sigmoid(tf.matmul(train_scaled, w) + b)
hypothesis

<tf.Tensor: id=32, shape=(455, 1), dtype=float32, numpy=
array([[0.91964334],
       [0.10414162],
       [0.82337296],
       [0.6369169 ],
       [0.9011744 ],
       [0.58958113],
       [0.31974596],
       [0.7374135 ],
       [0.761508  ],
       [0.7893415 ],
       [0.8394147 ],
       [0.23063067],
       [0.90862584],
       [0.5002521 ],
       [0.7084362 ],
       [0.59987426],
       [0.77379405],
       [0.78466624],
       [0.42972746],
       [0.29977807],
       [0.50970685],
       [0.1058625 ],
       [0.54150426],
       [0.54590946],
       [0.04952678],
       [0.81065416],
       [0.5935625 ],
       [0.6699424 ],
       [0.7118197 ],
       [0.6919981 ],
       [0.7011708 ],
       [0.68469393],
       [0.8786967 ],
       [0.7491182 ],
       [0.81774724],
       [0.73419726],
       [0.9521642 ],
       [0.93956274],
       [0.60427177],
       [0.51387197],
       [0.3981533 ],
       [0.7851532 ],
       [0.22972086],
       [0.5912448 ],
       [0.83662564]

In [27]:
# optimizer 생성
optimizer = tf.train.AdamOptimizer(0.001)

In [28]:
# 반복해서 w와 b를 찾음

for step in range(100):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(train_scaled, w) + b)
        cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis))
        grads = tape.gradient(cost, [w,b])
    optimizer.apply_gradients(grads_and_vars=zip(grads, [w,b]))

    if step % 10 ==0:
        print('-'*50)
        print(f'step : {step}, cost : {cost.numpy()}, w : {w.numpy()}, b : {b.numpy()}')
        print('-'*50)

--------------------------------------------------
step : 0, cost : 0.559338390827179, w : [[-0.3542775 ]
 [-0.28306985]
 [ 0.07462971]
 [-0.0380059 ]
 [-0.43789795]
 [ 0.28538746]
 [ 0.14387242]
 [-0.2732712 ]
 [ 0.11815482]
 [-0.21943294]
 [ 0.19457309]
 [-0.16639592]
 [ 0.33983284]
 [-0.22675768]
 [-0.05354773]
 [-0.21158414]
 [-0.12790638]
 [-0.42345816]
 [-0.2426768 ]
 [-0.02246519]
 [ 0.1747111 ]
 [ 0.23637246]
 [-0.28005403]
 [ 0.02371087]
 [ 0.37759572]
 [-0.10922863]
 [-0.41063267]
 [-0.24842526]
 [ 0.40275478]
 [ 0.3862669 ]], b : [0.6058489]
--------------------------------------------------
--------------------------------------------------
step : 10, cost : 0.5171224474906921, w : [[-0.3642323 ]
 [-0.29303637]
 [ 0.06467553]
 [-0.04795929]
 [-0.44785172]
 [ 0.27544197]
 [ 0.13392621]
 [-0.2832231 ]
 [ 0.10819527]
 [-0.2094403 ]
 [ 0.18462557]
 [-0.15642981]
 [ 0.32988778]
 [-0.23670542]
 [-0.04358222]
 [-0.2014197 ]
 [-0.11783543]
 [-0.4262537 ]
 [-0.23270667]
 [-0.0124650

In [29]:
print(w, b)

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.43758687],
       [-0.3705871 ],
       [-0.00854006],
       [-0.12102823],
       [-0.52092963],
       [ 0.20447308],
       [ 0.06257159],
       [-0.3561317 ],
       [ 0.0334659 ],
       [-0.12824439],
       [ 0.11174894],
       [-0.08314761],
       [ 0.25743887],
       [-0.30916142],
       [ 0.0282028 ],
       [-0.10333458],
       [-0.02373126],
       [-0.31657556],
       [-0.15934986],
       [ 0.07005533],
       [ 0.09056062],
       [ 0.14764798],
       [-0.36404642],
       [-0.05987528],
       [ 0.28959385],
       [-0.19420046],
       [-0.4943896 ],
       [-0.33274737],
       [ 0.3144491 ],
       [ 0.29955   ]], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.6975574], dtype=float32)>


In [31]:
# 뽑아낸 w, b값으로 예측하기
predict = tf.sigmoid(tf.matmul(test_scaled, w) + b)
predict01 = tf.cast(predict > 0.5, dtype=tf.float32)
predict01

<tf.Tensor: id=6442, shape=(114, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
     

In [32]:
# 예측값과 실제값이 같은지 확인후 정확도 뽑아내기
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype='float32'))
accuracy

<tf.Tensor: id=6447, shape=(), dtype=float32, numpy=0.8684211>

텐서플로2

In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [4]:
tf.enable_eager_execution()

In [6]:
cancer = datasets.load_breast_cancer()
cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [7]:
X = cancer.data
y = cancer.target
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float64 (569,) int32


In [8]:
X = np.array(X, dtype='float32')
y = np.array(y, dtype='float32')
y = y.reshape(-1,1)
print(X.shape, X.dtype, y.shape, y.dtype)

(569, 30) float32 (569, 1) float32


In [9]:
#데이터 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455, 1) (114, 1)


In [11]:
# 표준화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

In [12]:
model = Sequential()
model.add(Dense(1, input_dim=30, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________
